from .core_analytics_statistics import MODULE_CORE_ANALYTICS_STATISTICS
from .core_analytics_full_rebuild import (
    MODULE_1_REBUILT as MODULE_1,
    MODULE_2_REBUILT as MODULE_2,
    MODULE_3_REBUILT as MODULE_3,
    MODULE_4_REBUILT as MODULE_4,
    MODULE_5_REBUILT as MODULE_5,
)

ALL_MODULES = [
    MODULE_CORE_ANALYTICS_STATISTICS,
    MODULE_1,
    MODULE_2,
    MODULE_3,
    MODULE_4,
    MODULE_5,
]
