GLOSSARY = [
    # Python Foundations
    {"term": "Variable", "definition": "A named container that stores a value. Like a labeled box. Example: age = 25", "module": "Python"},
    {"term": "String", "definition": "Text data in Python, wrapped in quotes. Example: name = 'Alice'", "module": "Python"},
    {"term": "Integer (int)", "definition": "A whole number with no decimal point. Example: count = 42", "module": "Python"},
    {"term": "Float", "definition": "A number with a decimal point. Example: gpa = 3.85", "module": "Python"},
    {"term": "Boolean", "definition": "A True or False value. Named after mathematician George Boole. Example: is_enrolled = True", "module": "Python"},
    {"term": "Function", "definition": "A reusable block of code with a name. Defined with 'def', called by name. Example: def greet(name): return 'Hello ' + name", "module": "Python"},
    {"term": "Parameter", "definition": "A variable in a function definition that receives an input. Example: in def add(x, y), x and y are parameters.", "module": "Python"},
    {"term": "Return", "definition": "The keyword that sends a value back from a function to whoever called it.", "module": "Python"},
    {"term": "List", "definition": "An ordered, mutable collection of items. Example: scores = [85, 92, 78]", "module": "Python"},
    {"term": "Dictionary", "definition": "A collection of key-value pairs. Like a lookup table. Example: {'name': 'Alice', 'gpa': 3.8}", "module": "Python"},
    {"term": "Index", "definition": "The position of an item in a list or string, starting at 0. scores[0] is the first item.", "module": "Python"},
    {"term": "Loop", "definition": "Code that repeats. 'for' loops iterate over sequences; 'while' loops repeat while a condition is True.", "module": "Python"},
    {"term": "Conditional (if/elif/else)", "definition": "Code that runs only when certain conditions are met. Python's decision-making tool.", "module": "Python"},
    {"term": "f-string", "definition": "A formatted string that lets you embed variables: f'Hello, {name}!'. The f prefix makes it an f-string.", "module": "Python"},
    {"term": "Indentation", "definition": "The spaces at the start of a line that define code blocks in Python. 4 spaces is standard.", "module": "Python"},
    {"term": "List Comprehension", "definition": "A concise way to create lists: [x*2 for x in numbers]. Equivalent to a for loop.", "module": "Python"},
    {"term": "None", "definition": "Python's null value — represents nothing or absence of a value. A function without return gives None.", "module": "Python"},
    {"term": "Import", "definition": "Load an external library or module. Example: import pandas as pd", "module": "Python"},

    # Data Analytics
    {"term": "NumPy", "definition": "Numerical Python — a library for fast array operations and math. Foundation of data science.", "module": "Data Analytics"},
    {"term": "Array", "definition": "A NumPy data structure like a list but faster and math-enabled. np.array([1,2,3])", "module": "Data Analytics"},
    {"term": "Pandas", "definition": "The most important data analysis library. Provides DataFrames — tables of data — for Python.", "module": "Data Analytics"},
    {"term": "DataFrame", "definition": "A 2D table with labeled rows and columns. Like an Excel spreadsheet in Python. The core Pandas structure.", "module": "Data Analytics"},
    {"term": "Series", "definition": "A single column of a DataFrame. A 1D labeled array.", "module": "Data Analytics"},
    {"term": "CSV", "definition": "Comma-Separated Values — a plain text file format for storing tabular data. Loaded with pd.read_csv().", "module": "Data Analytics"},
    {"term": "NaN", "definition": "Not a Number — represents a missing value in a dataset. Check with df.isnull()", "module": "Data Analytics"},
    {"term": "Missing Values", "definition": "Gaps in a dataset where data wasn't recorded. Handled by dropping (dropna) or filling (fillna).", "module": "Data Analytics"},
    {"term": "Groupby", "definition": "Split a DataFrame by category, apply a function (mean/sum), combine results. df.groupby('region')['sales'].sum()", "module": "Data Analytics"},
    {"term": "Aggregation", "definition": "Computing a summary statistic (mean, sum, count, max) across a group of values.", "module": "Data Analytics"},
    {"term": "Mean", "definition": "The average — sum divided by count. Sensitive to outliers.", "module": "Data Analytics"},
    {"term": "Median", "definition": "The middle value when sorted. Robust to outliers — preferred for skewed data.", "module": "Data Analytics"},
    {"term": "Standard Deviation (Std)", "definition": "Measures how spread out values are from the mean. Higher std = more spread.", "module": "Data Analytics"},
    {"term": "Correlation", "definition": "A measure (-1 to 1) of how strongly two variables move together. 1=perfect positive, 0=none, -1=perfect negative.", "module": "Data Analytics"},
    {"term": "Outlier", "definition": "A data point that is far from the rest. Can distort mean and other statistics.", "module": "Data Analytics"},
    {"term": "Matplotlib", "definition": "Python's core plotting library. Creates bar charts, line charts, scatter plots, and more.", "module": "Data Analytics"},
    {"term": "Seaborn", "definition": "A higher-level plotting library built on matplotlib. Creates prettier charts with less code.", "module": "Data Analytics"},
    {"term": "Histogram", "definition": "A chart showing the distribution of a numerical variable — how often each range of values appears.", "module": "Data Analytics"},
    {"term": "Boolean Indexing", "definition": "Filtering a DataFrame or array using a condition: df[df['gpa'] > 3.5]", "module": "Data Analytics"},
    {"term": "dtype", "definition": "Data type of a column (int64, float64, object/string, bool). Check with df.dtypes.", "module": "Data Analytics"},

    # SQL
    {"term": "SQL", "definition": "Structured Query Language — used to query and manipulate relational databases.", "module": "SQL"},
    {"term": "Database", "definition": "An organized collection of structured data stored electronically.", "module": "SQL"},
    {"term": "Table", "definition": "A structured dataset with rows (records) and columns (fields) in a database.", "module": "SQL"},
    {"term": "Primary Key", "definition": "A unique identifier for each row in a table. No two rows have the same primary key.", "module": "SQL"},
    {"term": "Foreign Key", "definition": "A column that links to the primary key of another table, creating a relationship.", "module": "SQL"},
    {"term": "JOIN", "definition": "Combining rows from two or more tables based on a shared column. INNER JOIN returns matching rows only.", "module": "SQL"},
    {"term": "SELECT", "definition": "SQL command to retrieve data: SELECT column FROM table WHERE condition", "module": "SQL"},
    {"term": "WHERE", "definition": "SQL clause to filter rows: WHERE age > 30", "module": "SQL"},
    {"term": "GROUP BY", "definition": "SQL clause to aggregate rows by a column: GROUP BY region", "module": "SQL"},

    # Machine Learning
    {"term": "Machine Learning (ML)", "definition": "Teaching computers to learn patterns from data instead of following explicit rules.", "module": "ML"},
    {"term": "Supervised Learning", "definition": "ML where the model learns from labeled examples (input + correct output). Includes regression and classification.", "module": "ML"},
    {"term": "Unsupervised Learning", "definition": "ML where the model finds patterns in unlabeled data. Includes clustering and dimensionality reduction.", "module": "ML"},
    {"term": "Feature", "definition": "An input variable used to make a prediction. Also called an independent variable or predictor.", "module": "ML"},
    {"term": "Label / Target", "definition": "The output variable the model is trying to predict. Also called the dependent variable.", "module": "ML"},
    {"term": "Training Data", "definition": "The dataset used to teach the model. The model learns patterns from this data.", "module": "ML"},
    {"term": "Test Data", "definition": "Data withheld from training. Used to evaluate how well the model generalizes.", "module": "ML"},
    {"term": "Overfitting", "definition": "When a model learns the training data too well (including noise) and performs poorly on new data.", "module": "ML"},
    {"term": "scikit-learn", "definition": "The most popular Python ML library. Provides tools for preprocessing, training, and evaluating models.", "module": "ML"},
    {"term": "Accuracy", "definition": "The fraction of predictions that are correct. accuracy = correct / total", "module": "ML"},
    {"term": "Regression", "definition": "Predicting a continuous numerical value. Example: predicting house prices.", "module": "ML"},
    {"term": "Classification", "definition": "Predicting a category or class. Example: spam vs. not spam.", "module": "ML"},

    # AI & LLMs
    {"term": "LLM (Large Language Model)", "definition": "An AI model trained on massive text data that can generate and understand language. Examples: Claude, GPT-4.", "module": "AI"},
    {"term": "Generative AI", "definition": "AI that creates new content (text, images, code) rather than just classifying or predicting.", "module": "AI"},
    {"term": "Prompt", "definition": "The input text you send to an AI model. The quality of your prompt greatly affects the response.", "module": "AI"},
    {"term": "Token", "definition": "The basic unit an LLM processes — roughly 3/4 of a word. 'Hello world' = ~2 tokens.", "module": "AI"},
    {"term": "Context Window", "definition": "The maximum amount of text an LLM can process at once (input + output combined).", "module": "AI"},
    {"term": "Prompt Engineering", "definition": "The practice of crafting effective prompts to get better outputs from AI models.", "module": "AI"},
    {"term": "XML Tags", "definition": "Structured markers (<instructions>, <context>, etc.) used to organize prompts and help AI parse different sections.", "module": "AI"},
    {"term": "API (Application Programming Interface)", "definition": "A way for programs to talk to each other. You call the Claude API to use Claude in your own code.", "module": "AI"},
    {"term": "Streaming", "definition": "Receiving AI output token-by-token as it's generated, instead of waiting for the full response.", "module": "AI"},
    {"term": "AI Agent", "definition": "An AI system that can take actions, use tools, and work through multi-step tasks autonomously.", "module": "AI"},
    {"term": "Tool Calling / Function Calling", "definition": "An AI capability where the model can invoke external functions (search, calculate, query a DB) to complete tasks.", "module": "AI"},
]
